# fly.toml app configuration file generated for megadoug-blog-backend on 2023-09-07T17:08:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "megadoug-blog-backend"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
